### PR TITLE
graph-builder: move plugins to cincinnati crate and catalog, and make plugins configurable

### LINKED ISSUE #237: Example run for graph-builder errors out
$ export CINCINNATI_REPO="redhat/openshift-cincinnati-test-public-manual"
$ export CINCINNATI_REGISTRY="https://quay.io"
$ cargo run --package graph-builder -- --service.address 0.0.0.0 --upstream.registry.url "${CINCINNATI_REGISTRY}" --upstream.registry.repository "${CINCINNATI_REPO}" 
    Finished dev [unoptimized + debuginfo] target(s) in 0.16s
     Running `target/debug/graph-builder --service.address 0.0.0.0 --upstream.registry.url 'https://quay.io' --upstream.registry.repository redhat/openshift-cincinnati-test-public-manual`
Error: Os { code: 2, kind: NotFound, message: "No such file or directory" }

could not open '""'

### PR DESCRIPTION
**Pull request by steveej**
This also reorganizes the imports, common code to all plugins, and
adjusts the terminology.

Fixes #237.

### CODE REVIEW

**Comment by vrutkovs** [comment]
Requires https://github.com/openshift/release/pull/7370 to pass (secret change)

**Comment by steveej** [comment]
@vrutkovs do you know why this happened in the `cargo-test` job?

```
 2020/02/29 01:16:33 error: unable to signal to artifacts container to terminate in pod cargo-test, triggering deletion: could not run remote command: unable to upgrade connection: container not found ("artifacts")
2020/02/29 01:16:33 error: unable to retrieve artifacts from pod cargo-test: could not read gzipped artifacts: unable to upgrade connection: container not found ("artifacts")
{"component":"entrypoint","file":"prow/entrypoint/run.g
```

I do expect the test itself to fail right now, but this doesn't look like the failure I expected.

**Comment by steveej** [comment]
/test ci/prow/cargo-test

Triggering a re-test as CI should be fixed after https://github.com/openshift/release/pull/7449.

**Comment by steveej** [comment]
Trying again.

/test cargo-test

**Comment by vrutkovs** [comment]
`test_get_labels` wants `CINCINNATI_TEST_QUAY_API_TOKEN`

**Comment by steveej** [comment]
> `test_get_labels` wants `CINCINNATI_TEST_QUAY_API_TOKEN`

The secret exists since there is no error around after reading them at https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_cincinnati/234/pull-ci-openshift-cincinnati-master-cargo-test/974#1:build-log.txt%3A15, but it's decipherable by the test:

```
thread 'net::private::test_wrong_auth' panicked at 'CINCINNATI_TEST_QUAY_API_TOKEN missing: NotUnicode("\xA9\xF85\u{14}
```

File: cincinnati/src/plugins/internal/graph_builder/github_openshift_secondary_metadata_scraper/plugin.rs [hunk 1]
```diff
@@ -28,6 +27,23 @@ pub struct GithubOpenshiftSecondaryMetadataScraperSettings {
...
+    /// Validate plugin configuration and fill in defaults.
+    pub fn deserialize_config(cfg: toml::Value) -> Fallible<Box<dyn PluginSettings>> {
+        let settings: Self = cfg.try_into()?;
+
+        ensure!(!settings.github_org.is_empty(), "empty github_org");
+        ensure!(!settings.github_repo.is_empty(), "empty github_repo");
+        ensure!(!settings.branch.is_empty(), "empty branch");
+        ensure!(
+            !settings.output_whitelist.is_empty(),
+            "empty output_whitelist"
```
Comment (vrutkovs) [inline cincinnati/src/plugins/internal/graph_builder/github_openshift_secondary_metadata_scraper/plugin.rs:43]: Lets add help text for `DEFAULT_OUTPUT_WHITELIST` in `cincinnati/src/plugins/internal/graph_builder`

File: cincinnati/src/plugins/internal/graph_builder/commons.rs [hunk 2]
```diff
@@ -0,0 +1,27 @@
+#[cfg(test)]
+pub mod tests {
+    //! Common functionality for graph-builder tests
+
+    use crate as cincinnati;
+
+    use cincinnati::plugins::internal::graph_builder::release;
+    use cincinnati::plugins::internal::graph_builder::release_scrape_dockerv2::registry;
+
+    fn init_logger() {
```
Comment (vrutkovs) [inline cincinnati/src/plugins/internal/graph_builder/commons.rs:10]: RLS warns that this is a dead code - needs `#![allow(dead_code)]`?

File: cincinnati/src/plugins/internal/graph_builder/release.rs [hunk 3]
```diff
@@ -0,0 +1,132 @@
...
+    pub next: Vec<Version>,
+    #[serde(default)]
+    pub metadata: HashMap<String, String>,
+}
+
+impl fmt::Display for Metadata {
+    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
+        write!(
+            f,
+            "Metadata {{ version: {}, previous: [{}], next: [{}], metadata: {:?} }}",
```
Comment (vrutkovs) [inline cincinnati/src/plugins/internal/graph_builder/release.rs:57]: `previous` and `next` would be string here, lets use quotes?

File: graph-builder/src/config/file.rs [hunk 4]
```diff
@@ -73,6 +99,9 @@ impl MergeOptions<Option<UpstreamOptions>> for AppSettings {
     fn try_merge(&mut self, opts: Option<UpstreamOptions>) -> Fallible<()> {
         if let Some(upstream) = opts {
             self.try_merge(upstream.registry)?;
+            if upstream.pause_secs.is_some() {
```
Comment (vrutkovs) [inline graph-builder/src/config/file.rs:102]: There are currently no requirements for Cincinnati releases (there aren't any really :) ). Do we want to keep it? I think its safe to remove it now, while we control the template and no disconnected installs are in the wild

File: hack/e2e.sh [hunk 5]
```diff
@@ -36,7 +36,9 @@ oc new-app -f template/cincinnati.yaml \
   -p GB_CINCINNATI_REPO="redhat/openshift-cincinnati-test-public-manual" \
   -p GB_CPU_REQUEST=50m \
   -p PE_CPU_REQUEST=50m \
-  -p RUST_BACKTRACE="1"
+  -p RUST_BACKTRACE="1" \
+  -p GB_REGISTRY_CREDENTIALS_PATH="" \
+  ;
```
Comment (vrutkovs) [inline hack/e2e.sh:41]: This would ignore the exit code of `oc new-app`, isn't it? Lets remove that

**Review by vrutkovs — CHANGES_REQUESTED** [review]
Few minor notes, looks good otherwise

File: graph-builder/src/config/file.rs (hunk 4 above)
Comment (steveej) [reply graph-builder/src/config/file.rs:102]: I will be very happy to remove it ASAP, but I'm hesitant to add the change to this PR. How about a separate ticket for rethinking the options?

File: hack/e2e.sh (hunk 5 above)
Comment (steveej) [reply hack/e2e.sh:41]: No, it's a trick which allows having a `\` behind each semantically meaningful line. The `;` explicitly terminates the command which is split across several lines. It doesn't change the behavior to the best of my knowledge. You may be confusing it for the construct
```
some_command || \
    :
```

File: cincinnati/src/plugins/internal/graph_builder/release.rs (hunk 3 above)
Comment (steveej) [reply cincinnati/src/plugins/internal/graph_builder/release.rs:57]: This is old code moved to a new place and it seems to work. Do you think we should touch it?

File: graph-builder/src/config/file.rs (hunk 4 above)
Comment (vrutkovs) [reply graph-builder/src/config/file.rs:102]: Do we have more deprecated options to remove though? I don't mind removing these later

File: hack/e2e.sh (hunk 5 above)
Comment (vrutkovs) [reply hack/e2e.sh:41]: Oh, pretty cool

File: cincinnati/src/plugins/internal/graph_builder/github_openshift_secondary_metadata_scraper/plugin.rs (hunk 1 above)
Comment (steveej) [reply cincinnati/src/plugins/internal/graph_builder/github_openshift_secondary_metadata_scraper/plugin.rs:43]: Do you mean that it can't be an empty string?

File: cincinnati/src/plugins/internal/graph_builder/commons.rs (hunk 2 above)
Comment (steveej) [reply cincinnati/src/plugins/internal/graph_builder/commons.rs:10]: Note that this is gated by `[cfg(test)]`. It probably depends on the configuration, as I don't get a warning from the RLS run by vscode. I also don't see any warnings when building any of the crates.

File: cincinnati/src/plugins/internal/graph_builder/github_openshift_secondary_metadata_scraper/plugin.rs (hunk 1 above)
Comment (steveej) [reply cincinnati/src/plugins/internal/graph_builder/github_openshift_secondary_metadata_scraper/plugin.rs:43]: I think we need a ticket to ensure proper plugin documentation, as this is not a single-case of lacking docstrings. I think the correct place to put documentation for this check would be on the `pub struct GithubOpenshiftSecondaryMetadataScraperSettings` itself. I added docstring for this there, but we should still follow-up with a more general pass over all plugin settings.

Comment (vrutkovs) [reply cincinnati/src/plugins/internal/graph_builder/github_openshift_secondary_metadata_scraper/plugin.rs:43]: Oh, okay, lets defer that

File: cincinnati/src/plugins/internal/graph_builder/commons.rs (hunk 2 above)
Comment (vrutkovs) [reply cincinnati/src/plugins/internal/graph_builder/commons.rs:10]: Odd, must be must config settings

File: cincinnati/src/plugins/internal/graph_builder/release.rs (hunk 3 above)
Comment (vrutkovs) [reply cincinnati/src/plugins/internal/graph_builder/release.rs:57]: Lets leave it in the backlog, its not really important

File: graph-builder/src/config/file.rs (hunk 4 above)
Comment (steveej) [reply graph-builder/src/config/file.rs:102]: I would like to remove all `UpstreamOptions` but I didn't want to touch all of them in this PR. I touched this one now because it's not in the correct place. I added this option to the `ServiceOptions`.

**Review by vrutkovs — APPROVED** [review]
/lgtm

**Review by vrutkovs — APPROVED** [review]
/lgtm
